# Generated by Django 2.2.3 on 2019-07-07 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='locked',
            field=models.BooleanField(default=False),
        ),
    ]
