# Generated by Django 2.2.3 on 2019-07-28 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_board_locked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cooldown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('board_id', models.IntegerField()),
                ('ip_address', models.GenericIPAddressField()),
            ],
        ),
    ]
